import { StyleSheet } from 'react-native';
import { COLORS, SHADOWS, TEXT_SHADOWS } from '../../constants/colors';
import { SPACING, BORDER_RADIUS, BORDER_WIDTH } from '../../constants/spacing';
import { FONT_SIZE, FONT_WEIGHT } from '../../constants/typography';

export const styles = StyleSheet.create({
    bg: { flex: 1, width: '100%', height: '100%', overflow: 'hidden' },
    safeArea: { flex: 1, width: '100%', overflow: 'hidden' },
    header: {
        backgroundColor: COLORS.headerBg,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: SPACING.lg,
        paddingVertical: SPACING.md,
        borderBottomWidth: BORDER_WIDTH.thin,
        borderBottomColor: COLORS.border,
    },
    headerBtn: {
        width: 44,
        alignItems: 'center',
    },
    headerArrow: {
        fontSize: 30,
        fontWeight: FONT_WEIGHT.black,
        color: COLORS.primary,
        ...TEXT_SHADOWS.md,
    },
    headerTitle: {
        fontSize: FONT_SIZE.xxl,
        fontWeight: FONT_WEIGHT.black,
        color: COLORS.white,
        letterSpacing: 1,
        ...TEXT_SHADOWS.md,
    },
    content: {
        flex: 1,
        paddingTop: SPACING.lg,
        paddingHorizontal: SPACING.lg,
        paddingBottom: SPACING.xl,
        alignItems: 'center',
        justifyContent: 'center',
    },
    card: {
        width: '92%',
        backgroundColor: COLORS.surface,
        borderRadius: BORDER_RADIUS.xl,
        borderWidth: BORDER_WIDTH.regular,
        borderColor: COLORS.border,
        padding: 6,
        alignItems: 'center',
        marginBottom: SPACING.lg,
        ...SHADOWS.lg,
    },
    logoMeet: {
        fontSize: 30,
        fontWeight: FONT_WEIGHT.black,
        color: COLORS.primary,
        letterSpacing: 2,
        lineHeight: 32,
        ...TEXT_SHADOWS.md,
    },
    logoStranger: {
        fontSize: 26,
        fontWeight: FONT_WEIGHT.black,
        color: COLORS.accent,
        letterSpacing: 2,
        marginBottom: SPACING.md,
        lineHeight: 28,
        ...TEXT_SHADOWS.md,
    },
    modalTitle: {
        fontSize: FONT_SIZE.xl,
        fontWeight: FONT_WEIGHT.black,
        color: COLORS.accent,
        textAlign: 'center',
        letterSpacing: 1,
        marginBottom: SPACING.lg,
        ...TEXT_SHADOWS.sm,
    },
    modalTitleRed: {
        fontSize: FONT_SIZE.xl,
        fontWeight: FONT_WEIGHT.black,
        color: COLORS.primary,
        textAlign: 'center',
        letterSpacing: 1,
        marginBottom: SPACING.lg,
        ...TEXT_SHADOWS.sm,
    },
    modalTitleBlue: {
        fontSize: FONT_SIZE.h3,
        fontWeight: FONT_WEIGHT.black,
        color: COLORS.accent,
        textAlign: 'center',
        letterSpacing: 1,
        marginBottom: SPACING.xl,
        ...TEXT_SHADOWS.md,
    },
    modalBody: {
        width: '100%',
        gap: 10,
        alignItems: 'flex-start',
        paddingLeft: 4,
    },
    listItem: {
        fontSize: FONT_SIZE.base,
        fontWeight: FONT_WEIGHT.bold,
        color: COLORS.accent,
        lineHeight: 24,
        textAlign: 'center',
        paddingRight: 10,
    },
    listItemAnswer: {
        fontSize: FONT_SIZE.sm,
        fontWeight: FONT_WEIGHT.semibold,
        color: COLORS.textSecondary,
        lineHeight: 20,
        marginTop: 2,
    },
    problemItem: {
        marginBottom: 10,
    },
    navButtons: {
        width: '100%',
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'flex-start',
        rowGap: 22,
        columnGap: 18,
    },
    navBtn: {
        width: '45%',
        backgroundColor: COLORS.surface,
        borderRadius: 18,
        borderWidth: BORDER_WIDTH.regular,
        borderColor: COLORS.border,
        paddingVertical: 18,
        paddingHorizontal: 10,
        alignItems: 'center',
        justifyContent: 'center',
        gap: SPACING.sm,
        minHeight: 130,
        ...SHADOWS.lg,
    },
    navBtnLabelRed: {
        fontSize: 14,
        fontWeight: FONT_WEIGHT.black,
        color: COLORS.primary,
        textAlign: 'center',
        letterSpacing: 0.5,
        ...TEXT_SHADOWS.sm,
    },
    navBtnLabelBlue: {
        fontSize: 14,
        fontWeight: FONT_WEIGHT.black,
        color: COLORS.accent,
        textAlign: 'center',
        letterSpacing: 0.5,
        ...TEXT_SHADOWS.sm,
    },
    navBtnIcon: { fontSize: FONT_SIZE.xxl },
    backButton: {
        fontSize: FONT_SIZE.lg,
        fontWeight: FONT_WEIGHT.black,
        color: COLORS.primary,
        letterSpacing: 0.5,
        ...TEXT_SHADOWS.sm,
    },
    supportForm: {
        width: '100%',
        gap: 14,
        marginTop: SPACING.lg,
    },
    supportLabel: {
        fontSize: 14,
        fontWeight: FONT_WEIGHT.black,
        color: COLORS.accent,
        letterSpacing: 0.5,
        marginLeft: 4,
    },
    supportInput: {
        borderWidth: BORDER_WIDTH.thin,
        borderColor: COLORS.border,
        borderRadius: BORDER_RADIUS.md,
        paddingVertical: SPACING.md,
        paddingHorizontal: 14,
        fontSize: 14,
        backgroundColor: COLORS.accentLight,
        fontWeight: FONT_WEIGHT.semibold,
        color: COLORS.text,
    },
    supportTextArea: {
        height: 100,
        textAlignVertical: 'top',
        paddingTop: SPACING.md,
    },
    supportButton: {
        backgroundColor: COLORS.primary,
        borderWidth: BORDER_WIDTH.regular,
        borderColor: COLORS.border,
        borderRadius: BORDER_RADIUS.xxl,
        paddingVertical: 14,
        paddingHorizontal: SPACING.xxl,
        alignItems: 'center',
        marginTop: SPACING.sm,
        ...SHADOWS.md,
    },
    supportButtonText: {
        fontSize: FONT_SIZE.lg,
        fontWeight: FONT_WEIGHT.black,
        color: COLORS.white,
        letterSpacing: 0.5,
        ...TEXT_SHADOWS.sm,
    },
});
