import { StyleSheet } from 'react-native';
import { COLORS, SHADOWS, TEXT_SHADOWS } from '../../constants/colors';
import { SPACING, BORDER_RADIUS, BORDER_WIDTH } from '../../constants/spacing';
import { FONT_SIZE, FONT_WEIGHT } from '../../constants/typography';

export const styles = StyleSheet.create({
    bg: {
        flex: 1,
        width: '100%',
        overflow: 'hidden',
    },
    safeArea: {
        flex: 1,
        width: '100%',
        overflow: 'hidden',
    },
    kav: {
        flex: 1,
        width: '100%',
    },
    center: {
        flex: 1,
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: SPACING.xl,
        paddingVertical: SPACING.xxl,
    },
    pageTitle: {
        fontSize: 52,
        fontWeight: FONT_WEIGHT.black,
        color: COLORS.accent,
        textAlign: 'center',
        letterSpacing: 3,
        marginBottom: SPACING.sm,
        ...TEXT_SHADOWS.lg,
    },
    pageSubtitle: {
        fontSize: FONT_SIZE.lg,
        fontWeight: FONT_WEIGHT.black,
        color: COLORS.primary,
        textAlign: 'center',
        letterSpacing: 1,
        marginTop: SPACING.sm,
        ...TEXT_SHADOWS.sm,
    },
    subtitleUnderline: {
        height: BORDER_WIDTH.regular,
        backgroundColor: COLORS.primary,
        width: '70%',
        alignSelf: 'center',
        marginTop: 6,
        marginBottom: SPACING.xl,
        borderRadius: 2,
    },
    card: {
        width: '90%',
        maxWidth: 420,
        alignSelf: 'center',
        backgroundColor: COLORS.surface,
        borderRadius: BORDER_RADIUS.lg,
        borderWidth: BORDER_WIDTH.regular,
        borderColor: COLORS.border,
        padding: SPACING.lg,
        ...SHADOWS.md,
    },
    fieldLabel: {
        fontSize: FONT_SIZE.md,
        fontWeight: FONT_WEIGHT.black,
        color: COLORS.accent,
        marginBottom: 6,
        letterSpacing: 1,
        ...TEXT_SHADOWS.sm,
    },
    input: {
        width: '100%',
        backgroundColor: COLORS.accentLight,
        borderRadius: BORDER_RADIUS.md,
        borderWidth: BORDER_WIDTH.thin,
        borderColor: COLORS.border,
        paddingHorizontal: 14,
        paddingVertical: SPACING.md,
        fontSize: FONT_SIZE.md,
        color: COLORS.text,
        marginBottom: 14,
    },
    forgotPassword: {
        fontSize: FONT_SIZE.sm,
        color: COLORS.textMuted,
        fontWeight: FONT_WEIGHT.semibold,
        textAlign: 'right',
        marginBottom: 14,
    },
    submitBtn: {
        width: '100%',
        backgroundColor: COLORS.surface,
        borderRadius: BORDER_RADIUS.xxl,
        borderWidth: BORDER_WIDTH.regular,
        borderColor: COLORS.border,
        paddingVertical: 14,
        alignItems: 'center',
        marginBottom: SPACING.md,
        ...SHADOWS.md,
    },
    submitBtnDisabled: {
        width: '100%',
        backgroundColor: COLORS.surface,
        borderRadius: BORDER_RADIUS.xxl,
        borderWidth: BORDER_WIDTH.regular,
        borderColor: COLORS.border,
        paddingVertical: 14,
        alignItems: 'center',
        marginBottom: SPACING.md,
        opacity: 0.5,
    },
    submitBtnText: {
        fontSize: FONT_SIZE.xxl,
        fontWeight: FONT_WEIGHT.black,
        color: COLORS.primary,
        letterSpacing: 2,
        ...TEXT_SHADOWS.md,
    },
    switchText: {
        fontSize: FONT_SIZE.sm,
        color: COLORS.textBrown,
        textAlign: 'center',
        fontWeight: FONT_WEIGHT.semibold,
        marginTop: SPACING.md,
    },
});
