import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
    bg: { flex: 1, overflow: 'hidden' },
    safeArea: { flex: 1, overflow: 'hidden' },
    flex: { flex: 1, overflow: 'hidden' },
    header: {
        backgroundColor: '#5ba3c7',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderBottomWidth: 2,
        borderBottomColor: '#000',
    },
    headerSideBtn: { padding: 4, width: 44, alignItems: 'center' },
    headerArrowRed: {
        fontSize: 28,
        fontWeight: '900',
        color: '#b20d1d',
        ...Platform.select({
            web: { textShadow: '2px 2px 0px #000' },
            default: {
                textShadowColor: '#000',
                textShadowOffset: { width: 2, height: 2 },
                textShadowRadius: 0,
            },
        }),
    },
    headerArrowDark: {
        fontSize: 28,
        fontWeight: '900',
        color: '#333',
        ...Platform.select({
            web: { textShadow: '2px 2px 0px #000' },
            default: {
                textShadowColor: '#000',
                textShadowOffset: { width: 2, height: 2 },
                textShadowRadius: 0,
            },
        }),
    },
    headerCenter: { flex: 1, alignItems: 'center' },
    headerTitle: {
        fontSize: 20,
        fontWeight: '900',
        color: '#2196F3',
        ...Platform.select({
            web: { textShadow: '2px 2px 0px #000' },
            default: {
                textShadowColor: '#000',
                textShadowOffset: { width: 2, height: 2 },
                textShadowRadius: 0,
            },
        }),
    },
    headerTitleRed: {
        color: '#b20d1d',
    },
    badgeRow: {
        alignItems: 'center',
        marginTop: -14,
        zIndex: 10,
        marginBottom: 6,
    },
    badge: {
        backgroundColor: '#fff9f1',
        borderRadius: 20,
        borderWidth: 3,
        borderColor: '#000',
        paddingHorizontal: 14,
        paddingVertical: 4,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        ...Platform.select({
            web: { boxShadow: '2px 2px 0px #000' },
            default: {
                shadowColor: '#000',
                shadowOffset: { width: 2, height: 2 },
                shadowOpacity: 1,
                shadowRadius: 0,
                elevation: 4,
            },
        }),
    },
    badgeText: {
        fontSize: 14,
        fontWeight: '900',
        color: '#2196F3',
        ...Platform.select({
            web: { textShadow: '1px 1px 0px #000' },
            default: {
                textShadowColor: '#000',
                textShadowOffset: { width: 1, height: 1 },
                textShadowRadius: 0,
            },
        }),
    },
    badgeIcon: { fontSize: 16 },
    card: {
        flex: 1,
        backgroundColor: '#e8f4fb',
        marginHorizontal: 12,
        borderRadius: 20,
        borderWidth: 3,
        borderColor: '#000',
        overflow: 'hidden',
        ...Platform.select({
            web: { boxShadow: '4px 4px 0px #000' },
            default: {
                shadowColor: '#000',
                shadowOffset: { width: 4, height: 4 },
                shadowOpacity: 1,
                shadowRadius: 0,
                elevation: 5,
            },
        }),
    },
    statusRow: {
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#c0dff0',
        backgroundColor: '#fff9f1',
    },
    statusText: { fontSize: 13, color: '#555', fontWeight: '600' },
    messagesList: { flex: 1 },
    messagesContent: { padding: 12, paddingBottom: 16 },
    inputRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 8,
        gap: 8,
    },
    textInput: {
        flex: 1,
        backgroundColor: '#fff9f1',
        borderRadius: 24,
        borderWidth: 2,
        borderColor: '#000',
        paddingHorizontal: 16,
        paddingVertical: 12,
        fontSize: 15,
        color: '#333',
        maxHeight: 100,
    },
    sendBtn: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#2196F3',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#000',
    },
    sendBtnDisabled: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#2196F3',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#000',
        opacity: 0.4,
    },
    sendBtnIcon: { fontSize: 20, color: '#fff', fontWeight: '700' },
});
