import { StyleSheet } from 'react-native';
import { COLORS, SHADOWS, TEXT_SHADOWS } from '../../constants/colors';
import { SPACING, BORDER_RADIUS, BORDER_WIDTH } from '../../constants/spacing';
import { FONT_SIZE, FONT_WEIGHT } from '../../constants/typography';

export const styles = StyleSheet.create({
    bg: { flex: 1, width: '100%', height: '100%', overflow: 'hidden' },
    safeArea: { flex: 1, overflow: 'hidden' },
    flex: { flex: 1, overflow: 'hidden' },
    header: {
        backgroundColor: COLORS.headerBg,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: SPACING.md,
        paddingVertical: 10,
        borderBottomWidth: BORDER_WIDTH.thin,
        borderBottomColor: COLORS.border,
    },
    headerSideBtn: { padding: 4, width: 44, alignItems: 'center' },
    headerArrowRed: {
        fontSize: FONT_SIZE.h3,
        fontWeight: FONT_WEIGHT.black,
        color: COLORS.primary,
        ...TEXT_SHADOWS.md,
    },
    headerArrowDark: {
        fontSize: FONT_SIZE.h3,
        fontWeight: FONT_WEIGHT.black,
        color: COLORS.text,
        ...TEXT_SHADOWS.md,
    },
    headerCenter: { flex: 1, alignItems: 'center' },
    headerTitle: {
        fontSize: FONT_SIZE.xl,
        fontWeight: FONT_WEIGHT.black,
        color: COLORS.accent,
        ...TEXT_SHADOWS.md,
    },
    headerTitleRed: {
        color: COLORS.primary,
    },
    badgeRow: {
        alignItems: 'center',
        marginTop: -14,
        zIndex: 10,
        marginBottom: SPACING.sm - 2,
    },
    badge: {
        backgroundColor: COLORS.surface,
        borderRadius: BORDER_RADIUS.xl,
        borderWidth: BORDER_WIDTH.regular,
        borderColor: COLORS.border,
        paddingHorizontal: SPACING.lg - 2,
        paddingVertical: 4,
        flexDirection: 'row',
        alignItems: 'center',
        gap: SPACING.sm - 2,
        ...SHADOWS.sm,
    },
    badgeText: {
        fontSize: FONT_SIZE.sm + 1,
        fontWeight: FONT_WEIGHT.black,
        color: COLORS.accent,
        ...TEXT_SHADOWS.sm,
    },
    badgeIcon: { fontSize: FONT_SIZE.md },
    card: {
        flex: 1,
        backgroundColor: COLORS.accentLight,
        marginHorizontal: SPACING.md,
        borderRadius: BORDER_RADIUS.xl,
        borderWidth: BORDER_WIDTH.regular,
        borderColor: COLORS.border,
        overflow: 'hidden',
        ...SHADOWS.lg,
    },
    statusRow: {
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.sm,
        borderBottomWidth: 1,
        borderBottomColor: '#c0dff0',
        backgroundColor: COLORS.surface,
    },
    statusText: { fontSize: FONT_SIZE.sm, color: COLORS.textSecondary, fontWeight: FONT_WEIGHT.semibold },
    messagesList: { flex: 1 },
    messagesContent: { padding: SPACING.md, paddingBottom: SPACING.lg },
    inputRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.sm,
        gap: SPACING.sm,
    },
    textInput: {
        flex: 1,
        backgroundColor: COLORS.surface,
        borderRadius: 24,
        borderWidth: BORDER_WIDTH.thin,
        borderColor: COLORS.border,
        paddingHorizontal: SPACING.lg,
        paddingVertical: SPACING.md,
        fontSize: FONT_SIZE.base,
        color: COLORS.text,
        maxHeight: 100,
    },
    sendBtn: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: COLORS.accent,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: BORDER_WIDTH.thin,
        borderColor: COLORS.border,
    },
    sendBtnDisabled: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: COLORS.accent,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: BORDER_WIDTH.thin,
        borderColor: COLORS.border,
        opacity: 0.4,
    },
    sendBtnIcon: { fontSize: FONT_SIZE.xl, color: COLORS.white, fontWeight: FONT_WEIGHT.bold },
});
